spring:
  application:
    name: config-default
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-uri:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
