spring:
  application:
    name: config-dev
eureka:
  instance:
    hostname: localhost
    ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
